server:
  port: 8090

spring:
  application:
    name: househelper-backend
  mvc:
    async:
      request-timeout: 5m
    servlet:
      load-on-startup: 1
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
